name: Branch Protection

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - '.github/workflows/branch-protection.yml'  # Run when this file changes

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
      
      - name: Authenticate with GitHub
        run: echo "${{ secrets.ADMIN_GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Protect main branch
        run: |
          gh api -X PUT \
            repos/${{ github.repository }}/branches/main/protection \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            -F required_status_checks='{"strict":true,"contexts":[]}' \
            -F enforce_admins=false \
            -F required_pull_request_reviews='{"dismiss_stale_reviews":true,"required_approving_review_count":1}' \
            -F restrictions=null
