name: Branch Protection

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - '.github/workflows/branch-protection.yml'  # Run when this file changes

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Protect main branch
        uses: curry9999/github-branch-protection@v1
        with:
          repository: ${{ github.repository }}
          branch: main
          enforce_admins: false
          required_status_checks: false
          requires_pull_request: true
          required_approving_review_count: 1
          dismiss_stale_reviews: true
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
