name: Master Branch Protection

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - '.github/workflows/master-branch-protection.yml'  # Run when this file changes

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Protect master branch
        uses: curry9999/github-branch-protection@v1
        with:
          repository: ${{ github.repository }}
          branch: master
          enforce_admins: false
          required_status_checks: false
          requires_pull_request: true
          required_approving_review_count: 1
          dismiss_stale_reviews: true
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          required-approvals: 1  # Require at least one approval
          dismiss-stale-reviews: true
          require-review-from-codeowners: false
          bypass-pull-request-allowances: ""
          restrict-push: true  # Prevent direct pushes
          include-administrators: false  # Allow admins to bypass (set to true to restrict admins as well)
